### ISSUE TITLE
Crash with newest release "1.4.2b" on Client, server works fine

### ISSUE THREAD

**Issue by ghost** [juancarloscp52/BedrockIfy#175]
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_338 failed
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.client.option.GameOptions.<init>(GameOptions:429)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:461)
	at net.minecraft.client.main.Main.method_44604(Main:205)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 11 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [bedrockify.mixins.json:client.features.chat.ChatHudMixin from mod bedrockify] from phase [DEFAULT] in config [bedrockify.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method method_27149 in bedrockify.mixins.json:client.features.chat.ChatHudMixin from mod bedrockify was not located in the target class net.minecraft.class_338. Using refmap bedrockify-refmap.json
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:436)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:412)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:340)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 14 more

**Comment by lonefelidae16** [comment]
I think 1.4.2b targets 1.19, *not* 1.19.1 or 1.19.2. Check your Minecraft version.

**Comment by ghost** [comment]
The server loads the mod fine, mhh weird. But I think this is maybe the case.

**Comment by lonefelidae16** [comment]
> The server loads the mod fine, mhh weird. But I think this is maybe the case.

Yes the server loads fine because of the mixin `ChatHudMixin` is in `client` section of `bedrockify.mixins.json:line14`, not for server. Plus, there are no other changes in 1.19.1/2 and 1.19.
This means that 1.4.2b can be used with 1.19.2 server without any problem.
https://github.com/juancarloscp52/BedrockIfy/blob/ab292247193edb9a625463536f2765a736ed698d/src/main/resources/bedrockify.mixins.json#L7-L14

**Comment by juancarloscp52** [comment]
Hi! In fact 1.4.2b only targets minecraft 1.19 as it is a backport of a fix on newer versions requested in #174. For 1.19.1/2 the latest version is 1.4.2. I'll update the curseforge/modrinth package name to make sure there is no confusion!

**Comment by MeikelLP** [comment]
@juancarloscp52 Can you change the "default download" for 1.19? It still references the 1.4.2b not 1.4.2. I fell into this pitfall as well.

**Comment by juancarloscp52** [comment]
Sadly curseforge does not allow to change the default download :(
