### ISSUE TITLE
Cannot load up game using the mod on MultiMC

### ISSUE THREAD

**Issue by Dinopirate06** [juancarloscp52/BedrockIfy#191]
I'm using MultiMC Version 0.6.16--3430 on lin64

using instance of minecraft of 1.19.1 with LWJGL 3.31, Forge 42.0.9, Intermediary Mappings 1.19.1, Fabric loader 0.14.10, and Quilt loader 0.17.4.

My Operating system is Pop!_OS with the KDE desktop environment

The mod I am using came from the source code and compiling it

log:
[13:43:48] [main/INFO]: Loading Minecraft 1.19.1 with Quilt Loader 0.17.4
[13:43:48] [ForkJoinPool-1-worker-2/WARN]: Warnings for mod "bedrockify"'s mod json:
- Version ${version} does not respect SemVer -- comparison support is limited. "version" at  at line 4 column 26 path $.version
[13:43:48] [main/ERROR]: Incompatible mod set!
org.quiltmc.loader.impl.FormattedException: org.quiltmc.loader.impl.discovery.ModResolutionException: Mod resolution failed!
	at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:214) ~[quilt-loader-0.17.4.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:141) ~[quilt-loader-0.17.4.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:70) [quilt-loader-0.17.4.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.17.4.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: org.quiltmc.loader.impl.discovery.ModResolutionException: Mod resolution failed!
	at org.quiltmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:427) ~[quilt-loader-0.17.4.jar:?]
	at org.quiltmc.loader.impl.QuiltLoaderImpl.setup(QuiltLoaderImpl.java:223) ~[quilt-loader-0.17.4.jar:?]
	at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:212) ~[quilt-loader-0.17.4.jar:?]
	... 11 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Mod at "/home/ethanboi/.local/share/multimc/instances/1.19.1/.minecraft/mods/bedrockify-1.5.1+mc1.19.1-sources.jar" has an invalid fabric.mod.json file!
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getException(ForkJoinTask.java:580) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getException(ForkJoinTask.java:909) ~[?:?]
	at org.quiltmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:410) ~[quilt-loader-0.17.4.jar:?]
	at org.quiltmc.loader.impl.QuiltLoaderImpl.setup(QuiltLoaderImpl.java:223) ~[quilt-loader-0.17.4.jar:?]
	at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:212) ~[quilt-loader-0.17.4.jar:?]
	... 11 more
Caused by: java.lang.RuntimeException: Mod at "/home/ethanboi/.local/share/multimc/instances/1.19.1/.minecraft/mods/bedrockify-1.5.1+mc1.19.1-sources.jar" has an invalid fabric.mod.json file!
	at org.quiltmc.loader.impl.discovery.ModResolver$ProcessAction.compute(ModResolver.java:222) ~[quilt-loader-0.17.4.jar:?]
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: org.quiltmc.loader.impl.metadata.ParseMetadataException: Error reading fabric.mod.json file for mod at unknown location: java.lang.NullPointerException: Cannot invoke "net.fabricmc.loader.impl.launch.FabricLauncher.isDevelopment()" because the return value of "net.fabricmc.loader.impl.launch.FabricLauncherBase.getLauncher()" is null
	at org.quiltmc.loader.impl.metadata.FabricModMetadataReader.parseMetadata(FabricModMetadataReader.java:85) ~[quilt-loader-0.17.4.jar:?]
	at org.quiltmc.loader.impl.metadata.FabricModMetadataReader.parseMetadata(FabricModMetadataReader.java:56) ~[quilt-loader-0.17.4.jar:?]
	at org.quiltmc.loader.impl.discovery.ModResolver$ProcessAction.compute(ModResolver.java:218) ~[quilt-loader-0.17.4.jar:?]
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.fabricmc.loader.impl.launch.FabricLauncher.isDevelopment()" because the return value of "net.fabricmc.loader.impl.launch.FabricLauncherBase.getLauncher()" is null
	at net.fabricmc.loader.impl.FabricLoaderImpl.isDevelopmentEnvironment(FabricLoaderImpl.java:376) ~[fabric-loader-0.14.10.jar:?]
	at org.quiltmc.loader.impl.metadata.FabricModMetadataReader.parseMetadata(FabricModMetadataReader.java:72) ~[quilt-loader-0.17.4.jar:?]
	at org.quiltmc.loader.impl.metadata.FabricModMetadataReader.parseMetadata(FabricModMetadataReader.java:56) ~[quilt-loader-0.17.4.jar:?]
	at org.quiltmc.loader.impl.discovery.ModResolver$ProcessAction.compute(ModResolver.java:218) ~[quilt-loader-0.17.4.jar:?]
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

**Comment by juancarloscp52** [comment]
Seems that you have downloaded the wrong bedrockIfy version. if you see in the mod file name, it ends in ...sources.jar. This file is only used for development. [Please try this file](https://www.curseforge.com/minecraft/mc-mods/bedrockify/files/4032335)
