### ISSUE TITLE
1.19.3 Crashing when trying to edit settings

### ISSUE THREAD

**Issue by Goober19** [juancarloscp52/BedrockIfy#197]
Bedrockify 1.5.2 for version 1.19.3 seems to launch just fine, but if you click on the in-game bedrockify settings to personalize it, Minecraft crashes
Minecraft Launcher Exit Code -1: [ The game crashed whilst mouseclicked event handler
Error: java.lang.NoSuchFieldError: field_15015 ]

**Comment by juancarloscp52** [comment]
does it happens when opening the menu, while editing a setting, or while saving changes? Also, could you share a full crashlog? Thanks!

**Comment by Goober19** [comment]
It seems while editing a setting
The mod works, I can use the reach around placement, see my coords, and I can view the Bedrockify settings page but if I attempt to click on any of the "+ Bedrock Overlay..." , "+ GUI/Visual Improvements...", etc. the game crashes and shows this report:

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2022-12-17 13:43:48
Description: mouseClicked event handler

java.lang.NoSuchFieldError: field_15015
	at me.shedaniel.clothconfig2.gui.entries.SubCategoryListEntry$CategoryLabelWidget.method_25402(SubCategoryListEntry.java:252)
	at net.minecraft.class_4069.method_25402(class_4069.java:31)
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen$ListWidget.method_25402(ClothConfigScreen.java:417)
	at net.minecraft.class_4069.method_25402(class_4069.java:31)
	at me.shedaniel.clothconfig2.gui.AbstractConfigScreen.method_25402(AbstractConfigScreen.java:263)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:215)
	at net.minecraft.class_310.method_1523(class_310.java:1225)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.shedaniel.clothconfig2.gui.entries.SubCategoryListEntry$CategoryLabelWidget.method_25402(SubCategoryListEntry.java:252)
	at net.minecraft.class_4069.method_25402(class_4069.java:31)
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen$ListWidget.method_25402(ClothConfigScreen.java:417)
	at net.minecraft.class_4069.method_25402(class_4069.java:31)
	at me.shedaniel.clothconfig2.gui.AbstractConfigScreen.method_25402(AbstractConfigScreen.java:263)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)

-- Affected screen --
Details:
	Screen name: me.shedaniel.clothconfig2.gui.ClothConfigScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:215)
	at net.minecraft.class_310.method_1523(class_310.java:1225)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods, file/VanillaTweaks_r296621.zip, replaymod_lang
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2397)
	at net.minecraft.class_310.method_1514(class_310.java:800)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1110953352 bytes (1059 MiB) / 2181038080 bytes (2080 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Virtual Desktop Monitor
	Graphics card #0 vendor: Virtual Desktop, Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=15.39.56.845
	Graphics card #1 name: NVIDIA GeForce RTX 3070
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2488
	Graphics card #1 versionInfo: DriverVersion=31.0.15.2756
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37558.08
	Virtual memory used (MB): 16233.93
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 18.71
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		bedrockify: BedrockIfy 1.5.2+mc1.19.3
		cem: Custom Entity Models 0.7.1
			completeconfig-base: completeconfig-base 2.2.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.2.0
		cloth-config: Cloth Config v9 9.0.93
			cloth-basic-math: cloth-basic-math 0.6.1
		completeconfig: CompleteConfig 2.2.0
			coat: Coat 1.0.0-beta.19+mc22w44a
			completeconfig-gui-yacl: completeconfig-gui-yacl 2.2.0
		fabric-api: Fabric API 0.69.1+1.19.3
			fabric-api-base: Fabric API Base 0.4.19+8d1895cf85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.18+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.0.0+689f5e7185
			fabric-block-api-v1: Fabric Block API (v1) 1.0.3+12bfe4ea85
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.28+c6af733c85
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.9+49abcf7e85
			fabric-command-api-v1: Fabric Command API (v1) 1.2.19+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.1.15+49abcf7e85
			fabric-commands-v0: Fabric Commands (v0) 0.2.36+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.44+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.12+49abcf7e85
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.0+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.12+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.1.1+112a38be85
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.39+48349a3f85
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.5+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.37+422b77fb85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.39+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.28+2894d6df85
			fabric-item-api-v1: Fabric Item API (v1) 2.1.5+4d2c606385
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.8+d3d735d085
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.28+aaaf9d3385
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.26+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.8+2894d6df85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.18+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.22+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.12+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.29+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.25+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.14+d9ac3c3985
			fabric-networking-v0: Fabric Networking (v0) 0.3.31+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.2.0+e9dee00485
			fabric-particles-v1: Fabric Particles (v1) 1.0.18+fbde993d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.1+2608564685
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.1.0+2063beff85
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.23+11ba9c3b85
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.28+df3654b385
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.23+48349a3f85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.16+3067f46385
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.31+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.7+49abcf7e85
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.0+280be3ab85
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.3+a10d22bd85
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.39+1d4d0b5785
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.10+689f5e7185
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.6+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.12+82a2701785
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.1.0+0efcd39b85
		fabricloader: Fabric Loader 0.14.11
		fallingleaves: Falling Leaves 1.14.0+1.19.3
		indium: Indium 1.0.10+mc1.19.3
		iris: Iris 1.4.6
			io_github_douira_glsl-transformer: glsl-transformer 1.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		java: OpenJDK 64-Bit Server VM 17
		lithium: Lithium 0.10.4
		minecraft: Minecraft 1.19.3
		modmenu: Mod Menu 5.0.2
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		replaymod: Replay Mod 1.19.3-2.6.10
		smoothboot: Smooth Boot 1.19-1.7.1
		sodium: Sodium 0.4.6+build.20
		starlight: Starlight 1.1.1+fabric.ae22326
		vivecraft: Vivecraft 1.19.3-0.0.13
	Loaded Shaderpack: ComplementaryShaders_v4.6.zip
		Profile: HIGH (+16 options changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.11-1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 3.2.0 NVIDIA 527.56, NVIDIA Corporation
	Window size: 1920x1057
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/VanillaTweaks_r296621.zip
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 5600X 6-Core Processor

**Comment by juancarloscp52** [comment]
Oh ok, it is caused by cloth config. Your instance is using 9.0.93 which only works for 1.19.3 pre release. Bedrockify includes cloth config 9.0.94 but is being overwritten by some other mod, or because another version has been maually installed.

Try to download the latest version [from here](https://www.curseforge.com/minecraft/mc-mods/cloth-config/files) and see if ti works.

**Comment by juancarloscp52** [comment]
After checking the mods one by one, seems like [falling leaves is using the pre release version](https://github.com/RandomMcSomethin/fallingleaves/blob/587a4a127aef066ef96d1e79d736ad9d1fb73152/gradle.properties#L18). Not sure if there are other mods with the same problem. Try disabling it and see if the problem persists

**Comment by Goober19** [comment]
Thank you so much, its working! I was able to keep the falling leaves just had to change the cloth config. We recently converted our bedrock world to java and miss some of the quality of life features, and now we got em!

**Comment by juancarloscp52** [comment]
Awesome :)
