### ISSUE TITLE
Conflict with Fabrication Mod

### ISSUE THREAD

**Issue by Afrocntrik** [juancarloscp52/BedrockIfy#33]
The game crashes due to [Fabrication](https://www.curseforge.com/minecraft/mc-mods/fabrication)'s special configuration screen not allowing the Panorama to be rendered.
Thread: Render thread
Stacktrace:
	at net.minecraft.class_350.redirect$zjn000$renderPanorama(class_350.java:621)
	at net.minecraft.class_350.method_25394(class_350.java:179)
	at io.github.prospector.modmenu.gui.ModsScreen.method_25394(ModsScreen.java:253)
	at com.unascribed.fabrication.client.FabricationConfigScreen.method_25394(FabricationConfigScreen.java:254)
Mods: BedrockIfy 0.2.0, Fabric API 0.26.0+1.16, & Mod Menu v1.14.10

**Comment by juancarloscp52** [comment]
Thanks for reporting this issue! I'll try to push a fix for the next version. For now, you can disable "client.features.panoramaBackground" mixin in the Mixins tab in the BedrockIfy Settings menu (Make sure you are using bedrockIfy 0.2.0+) an restart the game.

**Comment by juancarloscp52** [comment]
With the last version of BedrockIfy (0.2.1) This issue has been fixed and you should be able to run BedrockIfy and Fabrication with "Panorama Backgrounds" enabled!!!
